import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Providers from "./components/providers";
import "./globals.css";
import HamburgerMenu from "./components/hamburgerMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <div className="flex flex-row justify-between items-center w-full py-2">
            <h1 className="px-4 text-3xl font-bold">Happie</h1>
            <HamburgerMenu />
          </div>
        </header>
        <main className="text-lg">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
